version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=idus
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/Dev/docekr/mysql/idus:/var/lib/mysql