spring:
  datasource:
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/idus?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.type: trace


