spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/reward?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    hikari:
      password: 1234
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.type: trace


